name: Node CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [8.x]
        os: [windows-2019,macOS-1.14]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and start
      run: |
        npm install
        npm run build --if-present
        npm start
      env:
        CI: true
